# future_report.yml
name: 実装・追加
description: 新機能の実装・追加はこちら
labels: ["feature"]
title: "Feature: "
body:
  - type: textarea
    id: overview
    attributes:
      label: 概要
      description: |
        新機能の概要を記載してください
    validations:
      required: true
  - type: textarea
    id: supplement
    attributes:
      label: 補足
      description: |
        補足事項があれば記載してください．また，見た目に関係する場合はスクリーンショット等を貼り付けてください．
    validations:
      required: true
  - type: textarea
    id: task
    attributes:
      label: タスク
      description: 実装・追加するタスクを記載してください．
      value: |
        - []
        - []
        - []
        ...
    validations:
      required: true
  - type: textarea
    id: manager
    attributes:
      label: 担当者
      description: Issue作成者，実装担当者（いれば）を記載してください．
      value: |
        issue作成者: @
        実装担当者: @
